activePeriod:
  keyWords:
    - "Termen limita"
    - "Termen limită"
    - "Termen limita:"
    - "Termen limită:"
  regex:
    - "(.termen.)"
budget:
  keyWords:
    - "Buget apel"
    - "Buget apel:"
    - "Buget"
    - "Buget:"
    - "Fonduri"
    - "Fonduri:"
    - "Fonduri alocate"
    - "Fonduri alocate:"
  regex:
    - "(.termen.)"